FROM node:13
WORKDIR /usr/node/server

COPY package.json yarn.lock ./
COPY ./prisma ./prisma
RUN yarn install --frozen-lockfile

COPY nodemon.json tsconfig.json ./
COPY ./src ./src

ENV NODE_ENV development
EXPOSE 4000
CMD yarn run nodemon --inspect=0.0.0.0 ./src/index.ts
