version: '3.7'

volumes:
  database:
    external: true
    name: database
  redis:
    external: true
    name: redis

services:
  redis:
    image: redis
    volumes:
      - redis:/data
    expose:
      - 6379

  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - database:/data/postgres
    expose:
      - 5432

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:changeme@database:5432/kuiz
      REDIS_HOST: redis
    volumes:
      - ./src:/usr/node/server/src
    ports:
      - 4000:4000
      - 4100:9229
